### ISSUE TITLE
doesseems not to work properly when timeline and timelines plugin are installed together

### ISSUE THREAD

**Issue by Parlazo** [George-debug/obsidian-timeline#6]
this timeline will interfere with the timelines plugin and apply asome bad settings to the timelines vertical view
and it also does not display any thing in the time line codeblock when view
the timelines plugin is awesome
but i think also this timeline plugin has some reason and sould get fixed

**Comment by George-debug** [comment]
**Timelines is ugly** and is the reason I made this plugin, so I can have a nice-looking timeline for my project!
Both plugins use `timeline` as their tag for the code block. I don't plan on changing mine and I'm sure he/she doesn't want to do it either.

I plan on solving this issue by adding a new tag for `labeling` instead of `+` (credits to [taqyon](https://github.com/taqyon) for the idea):
```timeline-labeled
date:
title:
content:

date:
title:
content:
```
